; @FILE: SUBRUTINAS_TIEMPO_2V.ASM
; @AUTOR: ARREGUIN HERNANDEZ JULIO DAVID
; @BRIEF: ARCHIVO QUE CONTIENE LAS SUBRUTINAS DE 1, 2 Y 3 VARIABLES
; @DATE: 10/05/2025
; @VERSION: 0.1
; @DETAILS: ESTE ARCHIVO ES UNA VERSIÓN CASI IDENTICA
; QUE SU ANTECESORA (SUBRUTINAS_TIEMPO.ASM) CON LA
; DIRERENCIA QUE AQUÍ NO SE ENCUENTRAN  LAS SUBRU-
; TINAS DE TIEMPOS FIJOS; T300MS, T10MS, ..., ETC.
; YA QUE NO CONTEMPLABAN LOS CICLOS DE MÁQUINA USA-
; DOS EN LA LLAMADA Y RETORNO DE LA SUBRUTINA.
; LOS TIEMPOS FIJOS AHORA SON MACROS CUYO NOMBRE DE
; ARCHIVO ES: MACROS_TIEMPOS_FIJOS.asm
; @Copyright (c) 2024

T300MS:
			SUBT2V		.253,.169
			SUBT2V		.1,.1
			RETURN;

T10MS:
			SUBT3V		.1,.142,.10
			RETURN

T25MS:
			SUBT2V		.40,.88
			RETURN;

T500MS:
			SUBT2V		.0,.0
			SUBT2V		.102,.56
			RETURN




ST1V			NOP
				NOP
				NOP
				NOP
				DECFSZ		0X50,F
				GOTO		ST1V
				RETURN



ST2V:			MOVF		0X52,W
				MOVWF		0X53
DECRE2V:		NOP
				NOP
				NOP
				NOP
				DECFSZ		0X53,F
				GOTO		DECRE2V
				DECFSZ		0X51,F
				GOTO		ST2V
				RETURN	




ST3V:			MOVF		0X56,W
				MOVWF		0X57		;0X57<-VAR3
RECARGA3V:		MOVF		0X55,W
				MOVWF		0X58		;0X58<-VAR2
DECRE3V:		NOP
				NOP
				NOP
				NOP
				DECFSZ		0X58,F
				GOTO		DECRE3V
				DECFSZ		0X57,F
				GOTO		RECARGA3V
				DECFSZ		0X54,F
				GOTO		ST3V
				RETURN
			

